name: Build and push docker image to docker hub

on:
  push:
    branches:
      - 'main'

jobs:
  job1_build_push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: umerarshad123/app_gh:v1

  job2_deploy_updated_image:
    runs-on: [self-hosted, Linux, X64, staging]
    needs: job1_build_push_docker_image
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      -
        name: Pull and run updated docker image
        run: docker run -d -p 5000:5000 umerarshad123/app_gh:v1
        
